config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :kakao_accounts do
    collection do
      post  'set_uniq_key'
      post  'create_user_copy_account'
      get   'set_user_id'
    end
  end

  root 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/models/kakao_account.rb
class KakaoAccount < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_copy_accounts
end

app/models/user_copy_account.rb
class UserCopyAccount < ActiveRecord::Base
  belongs_to  :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.fetch(:game, {})
    end
end

app/controllers/kakao_accounts_controller.rb
class KakaoAccountsController < ApplicationController
  before_action :set_kakao_account, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :except => [:set_uniq_key, :set_user_id, :create_user_copy_account]

  # GET /kakao_accounts
  # GET /kakao_accounts.json
  def index
    game_id = params[:game_id]
    @kakao_accounts = KakaoAccount.where(game_id: game_id, is_true: true).order("id desc").limit(200)
    @account_ids = []
    @account_ids = UserCopyAccount.where(user_id: session[:user_id]).pluck(:account_id) if session[:user_id]
    @game_uniq_key = "#{SecureRandom.urlsafe_base64(nil, false)}-#{SecureRandom.urlsafe_base64(nil, false)}-#{SecureRandom.urlsafe_base64(nil, false)}"
  end
  
  def set_uniq_key
    user = User.create(game_uniq_key: params[:game_uniq_key])
    session[:user_id] = user.id
    render json: {user_id: user.id}
  end
  
  def set_user_id
    user = User.find_by_game_uniq_key(params[:game_uniq_key])
    session[:user_id] = user.id
    render json: {status: :ok}
  end
  
  def create_user_copy_account
    user = User.find_by_game_uniq_key(params[:game_uniq_key])
    copy_account = user.user_copy_accounts.where(account_id: params[:account_id])
    user.user_copy_accounts.create(account_id: params[:account_id]) if copy_account.blank?
    render json: {status: :ok}
  end

  # GET /kakao_accounts/1
  # GET /kakao_accounts/1.json
  def show
  end

  # GET /kakao_accounts/new
  def new
    @kakao_account = KakaoAccount.new
  end

  # GET /kakao_accounts/1/edit
  def edit
  end

  # POST /kakao_accounts
  # POST /kakao_accounts.json
  def create
    @kakao_account = KakaoAccount.new(kakao_account_params)

    respond_to do |format|
      if @kakao_account.save
        format.html { redirect_to @kakao_account, notice: 'Kakao account was successfully created.' }
        format.json { render :show, status: :created, location: @kakao_account }
      else
        format.html { render :new }
        format.json { render json: @kakao_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kakao_accounts/1
  # PATCH/PUT /kakao_accounts/1.json
  def update
    respond_to do |format|
      if @kakao_account.update(kakao_account_params)
        format.html { redirect_to @kakao_account, notice: 'Kakao account was successfully updated.' }
        format.json { render :show, status: :ok, location: @kakao_account }
      else
        format.html { render :edit }
        format.json { render json: @kakao_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kakao_accounts/1
  # DELETE /kakao_accounts/1.json
  def destroy
    @kakao_account.destroy
    respond_to do |format|
      format.html { redirect_to kakao_accounts_url, notice: 'Kakao account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kakao_account
      @kakao_account = KakaoAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kakao_account_params
      params.fetch(:kakao_account, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/kakao_accounts_helper.rb
module KakaoAccountsHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div style="width:100%; text-align: center;">
	<% @games.each do |game| %>
		<a href="#" onclick="go(<%=game.id%>);">
			<div>
				<img src="<%=game.image_url%>" style="width:100px; display: block; margin-left: auto; margin-right: auto;">
			</div>
		</a>
	<% end %>
</div>

<script>
	function go(game_id){
		window.location = "<%=URL%>" + "kakao_accounts?game_id=" + game_id; 
	}
</script>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/kakao_accounts/_form.html.erb
<%= form_for(@kakao_account) do |f| %>
  <% if @kakao_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kakao_account.errors.count, "error") %> prohibited this kakao_account from being saved:</h2>

      <ul>
      <% @kakao_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kakao_accounts/edit.html.erb
<h1>Editing Kakao Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @kakao_account %> |
<%= link_to 'Back', kakao_accounts_path %>

app/views/kakao_accounts/index.html.erb
<div style="width:100%;">
	
	<table style="width:100%; border-collapse:collapse;">
		<% @kakao_accounts.each do |kakao_account| %>
		<tr id="account_<%=kakao_account.id%>" style="<%= @account_ids.index(kakao_account.id) ? "background-color: gray;" : "background-color: #DCDCDC;" %>">
			<td class="kakao_account" style="width:100%; margin-top:5px; padding:10px; line-height:20px;font-size:18px; border-bottom:1pt solid white;">
				<span style="float:left; padding:10px;"><%= kakao_account.account%></span>
				<span onclick="copyToClipboard('<%=kakao_account.id%>', '<%= kakao_account.account %>')" style="font-size:14px; background-color: #E6E6FA; float:right; padding:10px;">ID복사</span>
			</td>
		</tr>
		<% end %>
	</table>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
	var game_uniq_key = getCookie("game_uniq_key");
	if ( game_uniq_key == "") {
		var game_uniq_key = "<%= @game_uniq_key %>";
		var d = new Date();
		d.setYear(2026);
		var expires = "expires="+d.toGMTString();
		document.cookie = "game_uniq_key" + "=" + game_uniq_key + "; " + expires;
		$.ajax({
			url: "/kakao_accounts/set_uniq_key",
			dataType:'json',
			data: {game_uniq_key: game_uniq_key},
			type:'POST',
			success: function(data){
				document.cookie = "user_id" + "=" + data.user_id + "; " + expires;
			  }
			});
	} else {
		if("<%=session[:user_id]%>" == "") {
			$.ajax({
				url: "/kakao_accounts/set_user_id",
				dataType:'json',
				data: {game_uniq_key: game_uniq_key},
				type:'GET',
				success: function(data){
				}
			});
		}
	}
	

	function copyToClipboard(account_id, str) {
	  var $temp = $("<input>");
	  $("body").append($temp);
	  $temp.val(str).select();
	  document.execCommand("copy");
	  $temp.remove();
	  $.ajax({
	  	url: "/kakao_accounts/create_user_copy_account",
	  	dataType:'json',
	  	data: {account_id: account_id, game_uniq_key: game_uniq_key},
		type:'POST',
		success: function(data){
			$("#account_"+account_id).css("background-color","gray");
		}
	  });
	  $("#msg").text(str + " 복사 완료!!!");
	  $("#msg").show();
	  setTimeout(hide_msg, 1000);
	}
	
	function hide_msg() {
		$("#msg").hide();
	}
	
	function getCookie(cname) {
	    var name = cname + "=";
	    var ca = document.cookie.split(';');
	    for(var i = 0; i <ca.length; i++) {
	        var c = ca[i];
	        while (c.charAt(0)==' ') {
	            c = c.substring(1);
	        }
	        if (c.indexOf(name) == 0) {
	            return c.substring(name.length,c.length);
	        }
	    }
	    return "";
	}
	
</script>

app/views/kakao_accounts/new.html.erb
<h1>New Kakao Account</h1>

<%= render 'form' %>

<%= link_to 'Back', kakao_accounts_path %>

app/views/kakao_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_kakao_account_path(@kakao_account) %> |
<%= link_to 'Back', kakao_accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameFriends</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
	
	ga('create', 'UA-80063048-1', 'auto');
	ga('send', 'pageview');
  </script>
  
</head>
<body style="background-color: white;">


<% if request.env['HTTP_USER_AGENT'].downcase.match(/mobile/) %>
<div style="width:100%; margin: 0 auto; height:100%; background-color: #DCDCDC;">
	<div style="position:fixed; font-size:18px; top:0; background-color:orange; width:100%; left:0; height:50px; line-height:50px; color:white; text-align: center; font-weight: bold; z-index: 999;">겜친 만들기 - 모두의 마블</div>
	<div id="msg" style="width:100%; position:fixed; top:50px; background-color:#87AFC7; height:50px; line-height:50px; margin: auto 0; color:#F75D59; text-align: center; z-index: 100; display:none; font-size: 16px; font-weight:bold;"></div>
<% else %>
<!--pc-->
<div style="width:500px; margin: 0 auto; height:100%; background-color: #DCDCDC;">
	<div style="position:fixed; font-size:18px; top:0; background-color:orange; width:500px; height:50px; line-height:50px; color:white; text-align: center; font-weight: bold; z-index: 999;">겜친 만들기 - 모두의 마블</div>
	<div id="msg" style="width:500px; position:fixed; top:50px; background-color:#87AFC7; height:50px; line-height:50px; margin: auto 0; color:#F75D59; text-align: center; z-index: 100; display:none; font-size: 16px; font-weight:bold;"></div>
	
<% end %>
<% if request.env['HTTP_USER_AGENT'].downcase.match(/mobile/) %> 
	<div style="padding-top: 50px; text-align: center;">
	     <ins class="adsbygoogle"
	     style="display:inline-block;width:100%;height:50px"
	     data-ad-client="ca-pub-2840781308828288"
	     data-ad-slot="9297516855"></ins>
	</div>
<% else %>
<!-- 고급형 -->
	<div style="padding-top: 50px; padding-bottom: 10px;">
		<ins class="adsbygoogle"
	    	style="display:block"
	     	data-ad-client="ca-pub-2840781308828288"
	     	data-ad-slot="7820783651"
	     	data-ad-format="auto"></ins>
   </div>
<% end %>
			<div>
			<%= yield %>
			</div>
</div>
</body>
</html>

<style>
html, body {
    height: 100%;
}
</style>

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- 고급형 -->
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

<script>
  // function explode(){
  	// $(".example_responsive_1").css({
	   // "display" : "inline"
	// });
  // }
  // setTimeout(explode, 500);
  
	
</script>